// packages/skeleton-angular/projects/lib/src/lib/app-bar/app-bar.component.ts
import { Component, ContentChild, ContentChildren, ElementRef, Input, QueryList, TemplateRef } from '@angular/core';
import { AppBarProps } from './types';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'skeleton-app-bar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app-bar.component.html',
  styleUrl: './app-bar.component.css'
})
export class AppBar {
  // Root
  @Input() base: AppBarProps['base'] = 'w-full flex flex-col';
  @Input() background: AppBarProps['background'] = 'bg-surface-100-900';
  @Input() spaceY: AppBarProps['spaceY'] = 'space-y-4';
  @Input() border: AppBarProps['border'] = '';
  @Input() padding: AppBarProps['padding'] = 'p-4';
  @Input() shadow: AppBarProps['shadow'] = '';
  @Input() classes: AppBarProps['classes'] = '';
  // Toolbar
  @Input() toolbarBase: AppBarProps['toolbarBase'] = 'flex justify-between';
  @Input() toolbarGridCols: AppBarProps['toolbarGridCols'] = 'grid-cols-[auto_1fr_auto]';
  @Input() toolbarGap: AppBarProps['toolbarGap'] = 'gap-4';
  @Input() toolbarClasses: AppBarProps['toolbarClasses'] = '';
  // Lead
  @Input() leadBase: AppBarProps['leadBase'] = 'flex';
  @Input() leadSpaceX: AppBarProps['leadSpaceX'] = 'space-x-4 rtl:space-x-reverse';
  @Input() leadPadding: AppBarProps['leadPadding'] = '';
  @Input() leadClasses: AppBarProps['leadClasses'] = '';
  // Center
  @Input() centerBase: AppBarProps['centerBase'] = 'grow';
  @Input() centerAlign: AppBarProps['centerAlign'] = 'text-center';
  @Input() centerPadding: AppBarProps['centerPadding'] = '';
  @Input() centerClasses: AppBarProps['centerClasses'] = '';
  // Trail
  @Input() trailBase: AppBarProps['trailBase'] = 'flex';
  @Input() trailSpaceX: AppBarProps['trailSpaceX'] = 'space-x-4 rtl:space-x-reverse';
  @Input() trailPadding: AppBarProps['trailPadding'] = '';
  @Input() trailClasses: AppBarProps['trailClasses'] = '';
  // Headline
  @Input() headlineBase: AppBarProps['headlineBase'] = 'w-full';
  @Input() headlineClasses: AppBarProps['headlineClasses'] = '';
  // Snippets - This are named slots in Vue, found in the template
  // children, - This is the default content projection in Angular
  // lead,
  // trail,
  // headline
  @ContentChild('lead', { read: TemplateRef }) lead!: TemplateRef<any>;
  @ContentChild('trail', { read: TemplateRef }) trail!: TemplateRef<any>;
  @ContentChild('headline', { read: TemplateRef }) headline!: TemplateRef<any>;
}

<header
  [ngClass]="[base, background, spaceY, border, padding, shadow, classes]"
  role="toolbar"
  data-testid="app-bar"
>
  <section
    [ngClass]="[toolbarBase, toolbarGridCols, toolbarGap, toolbarClasses]"
  >
    @if (lead) {
      <div [ngClass]="[leadBase, leadSpaceX, leadPadding, leadClasses]">
        <ng-container [ngTemplateOutlet]="lead"></ng-container>
      </div>
    }

    <div [ngClass]="[centerBase, centerAlign, centerPadding, centerClasses]">
      <ng-content></ng-content>
    </div>

    @if (trail) {
      <div [ngClass]="[trailBase, trailSpaceX, trailPadding, trailClasses]">
        <ng-container [ngTemplateOutlet]="trail"></ng-container>
      </div>
    }
  </section>

  @if (headline) {
    <section [ngClass]="[headlineBase, headlineClasses]">
      <ng-container [ngTemplateOutlet]="headline"></ng-container>
    </section>
  }
</header>

// packages/skeleton-vue/src/lib/components/AppBar/AppBar.vue
<script lang="ts" setup>
import type { AppBarProps } from './types';

withDefaults(defineProps<AppBarProps>(), {
  // Root
  base: 'w-full flex flex-col',
  background: 'bg-surface-100-900',
  spaceY: 'space-y-4',
  border: '',
  padding: 'p-4',
  shadow: '',
  classes: '',
  // Toolbar
  toolbarBase: 'flex justify-between',
  toolbarGridCols: 'grid-cols-[auto_1fr_auto]',
  toolbarGap: 'gap-4',
  toolbarClasses: '',
  // Lead
  leadBase: 'flex',
  leadSpaceX: 'space-x-4 rtl:space-x-reverse',
  leadPadding: '',
  leadClasses: '',
  // Center
  centerBase: 'grow',
  centerAlign: 'text-center',
  centerPadding: '',
  centerClasses: '',
  // Trail
  trailBase: 'flex',
  trailSpaceX: 'space-x-4 rtl:space-x-reverse',
  trailPadding: '',
  trailClasses: '',
  // Headline
  headlineBase: 'w-full',
  headlineClasses: '',
  // Snippets - This are named slots in Vue, found in the template
  // children,
  // lead,
  // trail,
  // headline
});
</script>

<template>
  <header
    :class="`${base} ${background} ${spaceY} ${border} ${padding} ${shadow} ${classes}`"
    role="toolbar"
    data-testid="app-bar"
  >
    <section :class="`${toolbarBase} ${toolbarGridCols} ${toolbarGap} ${toolbarClasses}`">
      <div v-if="$slots.lead" :class="`${leadBase} ${leadSpaceX} ${leadPadding} ${leadClasses}`">
        <slot name="lead"></slot>
      </div>

      <div
        v-if="$slots.default"
        :class="`${centerBase} ${centerAlign} ${centerPadding} ${centerClasses}`"
      >
        <slot></slot>
      </div>

      <div
        v-if="$slots.trail"
        :class="`${trailBase} ${trailSpaceX} ${trailPadding} ${trailClasses}`"
      >
        <slot name="trail"></slot>
      </div>
    </section>

    <section v-if="$slots.headline" :class="`${headlineBase} ${headlineClasses}`">
      <slot name="headline"></slot>
    </section>
  </header>
</template>
