// packages/skeleton-angular/projects/lib/src/lib/avatar/avatar.component.ts
import { Component, Input } from '@angular/core';
import { AvatarProps } from './types';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'skeleton-avatar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './avatar.component.html',
  styleUrl: './avatar.component.css',
})
export class Avatar {
  @Input() src: AvatarProps['src'] = '';
  @Input() alt: AvatarProps['alt'] = '';
  @Input() filter: AvatarProps['filter'] = '';
  // Root
  @Input() base: AvatarProps['base'] = 'overflow-hidden isolate';
  @Input() background: AvatarProps['background'] = 'bg-surface-400-600';
  @Input() size: AvatarProps['size'] = 'size-16';
  @Input() font: AvatarProps['font'] = '';
  @Input() border: AvatarProps['border'] = '';
  @Input() rounded: AvatarProps['rounded'] = 'rounded-full';
  @Input() shadow: AvatarProps['shadow'] = '';
  @Input() classes: AvatarProps['classes'] = '';
  // Image
  @Input() imageBase: AvatarProps['imageBase'] = 'w-full object-cover';
  @Input() imageClasses: AvatarProps['imageClasses'] = '';
  // Snippets - This is achieved through (named) content projection
  // children

  get styleFilter() {
    return this.filter ? `url(${this.filter})` : ''
  }
}

<figure
  [ngClass]="[base, background, size, font, border, rounded, shadow, classes]"
  data-testId="avatar"
>
  @if (src) {
    <img
      v-if="src"
      [ngClass]="[imageBase, imageClasses]"
      [src]="src"
      [alt]="alt"
      [ngStyle]="{ filter: styleFilter }"
    />
  } @else {
    <ng-content></ng-content>
  }
</figure>

// packages/skeleton-vue/src/lib/components/Avatar/Avatar.vue
<script lang="ts" setup>
import type { AvatarProps } from './types';

const props = withDefaults(defineProps<AvatarProps>(), {
  src: '',
  alt: '',
  filter: '',
  // Root
  base: 'overflow-hidden isolate',
  background: 'bg-surface-400-600',
  size: 'size-16',
  font: '',
  border: '',
  rounded: 'rounded-full',
  shadow: '',
  classes: '',
  // Image
  imageBase: 'w-full object-cover',
  imageClasses: '',
  // Snippets - This are named slots in Vue, found in the template
  // children
});
</script>

<template>
  <figure
    :class="`${base} ${background} ${size} ${font} ${border} ${rounded} ${shadow} ${classes}`"
    data-testId="avatar"
  >
    <img
      v-if="src"
      :class="`${imageBase} ${imageClasses}`"
      :src
      :alt
      :style="{ filter: filter ? `url(${filter})` : '' }"
    />
    <template v-else-if="$slots.default">
      <slot></slot>
    </template>
  </figure>
</template>
