// packages/skeleton-vue/src/lib/components/Navigation/NavTile.vue
<script lang="ts" setup>
import { computed } from 'vue';
import { getNavigationContext } from './context';
import type { NavTileProps } from './types';

const emits = defineEmits<{
  onClick: [value: string];
}>();

const props = withDefaults(defineProps<NavTileProps>(), {
  id: undefined,
  href: undefined,
  target: undefined,
  label: undefined,
  labelExpanded: undefined,
  title: undefined,
  selected: false,
  // Root
  base: 'flex items-center',
  width: 'w-full',
  aspect: 'aspect-square',
  background: '',
  hover: 'hover:preset-filled-surface-50-950',
  active: 'preset-filled-primary-500',
  padding: 'p-2',
  gap: 'gap-1',
  rounded: 'rounded-container',
  classes: 'flex-col justify-center',
  // Expanded
  expandedPadding: 'py-3 px-4',
  expandedGap: 'gap-4',
  expandedClasses: '',
  // Label (base)
  labelBase: 'type-scale-1',
  labelClasses: '',
  // Label (expanded)
  labelExpandedBase: '',
  labelExpandedClasses: '',
  // Events
  // onclick: undefined,
  // Snippets
  // children
});

// Context
const ctx = getNavigationContext();

// Reactive
const element = computed(() => (props.href ? 'a' : 'button'));
const type = computed(() => (props.href ? undefined : 'button'));
const role = computed(() => (props.href ? undefined : 'button'));
const rxSize = computed(() => (ctx.parent === 'bar' ? `h-full` : `${props.aspect}`));
const classesCollapsed = computed(() => `${rxSize.value} ${props.padding} ${props.gap} ${props.classes}`);
const classesExtended = computed(
  () => `${props.expandedPadding} ${props.expandedGap} ${props.expandedClasses}`,
);
const rxMode = computed(() => {
  return ctx.expanded ? classesExtended.value : classesCollapsed.value;
});
const rxBackground = computed(() => {
  return props.selected || ctx.value === props.id
    ? props.active
    : `${props.background} ${props.hover}`;
});

function onClickHandler() {
  if (!props.id) return;

  emits('onClick', props.id);
  if (ctx.onSelectionHandler && props.id) ctx.onSelectionHandler(props.id);
}
</script>

<template>
  <component
    :is="element"
    :class="[base, width, rounded, rxBackground, rxMode]"
    :href
    :target
    :type
    :title
    :role
    @click="onClickHandler"
    tabindex="0"
    data-testid="nav-tile"
  >
    <!-- Icon -->
    <div v-if="$slots.default">
      <slot></slot>
    </div>
    <!-- Label (base) -->
    <div v-if="label && !ctx.expanded" :class="[labelBase, labelClasses]">{{ label }}</div>
    <!-- Label (expanded) -->
    <div v-if="labelExpanded && ctx.expanded" :class="[labelExpandedBase, labelExpandedClasses]">
      {{ labelExpanded }}
    </div>
  </component>
</template>

// packages/skeleton-angular/projects/lib/src/lib/components/navigation/nav-tile/nav-tile.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NavContextService } from '../nav-context.service';

@Component({
  selector: 'skeleton-nav-tile',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './nav-tile.component.html',
  styleUrl: './nav-tile.component.css',
})
export class NavTile {
  @Input() id?: string;
  @Input() href?: string;
  @Input() target: string = '_self';
  @Input() label?: string;
  @Input() labelExpanded?: string;
  @Input() title?: string;
  @Input() selected = false;
  // Root
  @Input() base = 'flex items-center';
  @Input() width = 'w-full';
  @Input() aspect = 'aspect-square';
  @Input() background = '';
  @Input() hover = 'hover:preset-filled-surface-50-950';
  @Input() active = 'preset-filled-primary-500';
  @Input() padding = 'p-2';
  @Input() gap = 'gap-1';
  @Input() rounded = 'rounded-container';
  @Input() classes = 'flex-col justify-center';
  // Expanded
  @Input() expandedPadding = 'py-3 px-4';
  @Input() expandedGap = 'gap-4';
  @Input() expandedClasses = '';
  // Label (base)
  @Input() labelBase = 'type-scale-1';
  @Input() labelClasses = '';
  // Label (expanded)
  @Input() labelExpandedBase = '';
  @Input() labelExpandedClasses = '';

  @Output() onClick = new EventEmitter<string>();

  constructor(public ctx: NavContextService) {}

  get element(): string {
    return this.href ? 'a' : 'button';
  }

  get type(): string | undefined {
    return this.href ? undefined : 'button';
  }

  get role(): string | undefined {
    return this.href ? undefined : 'button';
  }

  get rxSize(): string {
    return this.ctx.parent() === 'bar' ? 'h-full' : `${this.aspect}`;
  }

  get classesCollapsed(): string {
    return `${this.rxSize} ${this.padding} ${this.gap} ${this.classes}`;
  }

  get classesExtended(): string {
    return `${this.expandedPadding} ${this.expandedGap} ${this.expandedClasses}`;
  }

  get rxMode(): string {
    return this.ctx.expanded() ? this.classesExtended : this.classesCollapsed;
  }

  get rxBackground(): string {
    return this.selected || this.ctx.value() === this.id
      ? this.active
      : `${this.background} ${this.hover}`;
  }

  onClickHandler() {
    if (!this.id) return;

    this.onClick.emit(this.id);
    if (this.ctx.onSelectionHandler && this.id) {
      this.ctx.onSelectionHandler(this.id);
    }
  }

  get componentClasses(): string {
    return `${this.base} ${this.width} ${this.rounded} ${this.rxBackground} ${this.rxMode}`;
  }
}

<!-- <ng-container [ngSwitch]="element">
  <a
    *ngSwitchCase="'a'"
    [ngClass]="componentClasses"
    [href]="href"
    [target]="target"
    [attr.title]="title"
    [attr.role]="role"
    (click)="onClickHandler()"
    tabindex="0"
    data-testid="nav-tile"
  >
    <ng-content></ng-content>
    <div *ngIf="label && !ctx.expanded()" [ngClass]="[labelBase, labelClasses]">
      {{ label }}
    </div>
    <div
      *ngIf="labelExpanded && ctx.expanded()"
      [ngClass]="[labelExpandedBase, labelExpandedClasses]"
    >
      {{ labelExpanded }}
    </div>
  </a>

  <button
    *ngSwitchCase="'button'"
    [ngClass]="componentClasses"
    [attr.title]="title"
    [attr.type]="type"
    [attr.role]="role"
    (click)="onClickHandler()"
    tabindex="0"
    data-testid="nav-tile"
  >
    <ng-content></ng-content>
    <div *ngIf="label && !ctx.expanded()" [ngClass]="[labelBase, labelClasses]">
      {{ label }}
    </div>
    <div
      *ngIf="labelExpanded && ctx.expanded()"
      [ngClass]="[labelExpandedBase, labelExpandedClasses]"
    >
      {{ labelExpanded }}
    </div>
  </button>
</ng-container> -->
<ng-container [ngSwitch]="element">

  <!-- Define the common structure in an ng-template -->
  <ng-template #commonContent>
    <ng-content></ng-content>
    <div *ngIf="label && !ctx.expanded()" [ngClass]="[labelBase, labelClasses]">
      {{ label }}
    </div>
    <div
      *ngIf="labelExpanded && ctx.expanded()"
      [ngClass]="[labelExpandedBase, labelExpandedClasses]"
    >
      {{ labelExpanded }}
    </div>
  </ng-template>

  <!-- Use the ng-template within ngSwitchCase -->
  <a
    *ngSwitchCase="'a'"
    [ngClass]="componentClasses"
    [href]="href"
    [target]="target"
    [attr.title]="title"
    [attr.role]="role"
    (click)="onClickHandler()"
    tabindex="0"
    data-testid="nav-tile"
  >
    <ng-container *ngTemplateOutlet="commonContent"></ng-container>
  </a>

  <button
    *ngSwitchCase="'button'"
    [ngClass]="componentClasses"
    [attr.title]="title"
    [attr.type]="type"
    [attr.role]="role"
    (click)="onClickHandler()"
    tabindex="0"
    data-testid="nav-tile"
  >
    <ng-container *ngTemplateOutlet="commonContent"></ng-container>
  </button>

</ng-container>
