// packages/skeleton-vue/src/lib/components/Switch/Switch.vue
<script lang="ts" setup>
import { computed, onMounted, reactive } from 'vue';
import type { SwitchProps } from './types';

const emits = defineEmits<{
  onCheckedChange: [value: boolean];
}>();

const props = withDefaults(defineProps<SwitchProps>(), {
  // id: '', // Required
  // name: '', // Required
  checked: false,
  disabled: false,
  compact: false,
  // Aria
  labelledby: undefined,
  describedby: undefined,
  // Root (Track)
  base: 'inline cursor-pointer transition duration-200',
  stateInactive: 'preset-filled-surface-200-800',
  stateActive: 'preset-filled-primary-500',
  stateDisabled: 'opacity-50 cursor-not-allowed',
  width: 'w-10',
  height: 'h-6',
  padding: 'p-0.5',
  rounded: 'rounded-full',
  hover: 'hover:brightness-90 dark:hover:brightness-110',
  classes: '',
  // Thumb
  thumbBase: 'right-0 aspect-square h-full flex justify-center items-center text-right',
  thumbInactive: 'preset-filled-surface-50-950',
  thumbActive: 'bg-surface-50 text-surface-contrast-50',
  thumbRounded: 'rounded-full',
  thumbTranslateX: 'translate-x-4',
  thumbTransition: 'transition',
  thumbEase: 'ease-in-out',
  thumbDuration: 'duration-200',
  thumbClasses: '',
  // Icons
  iconInactiveBase: 'pointer-events-none',
  iconActiveBase: 'pointer-events-none',

  // Events - This are Emits in Vue, found in the defineEmits in the script
  // onCheckedChange: () => {}

  // Snippets - This are named slots in Vue, found in the template
  // inactiveChild,
  // activeChild
});

const state = reactive({
  base: props.base,
  height: props.height,
  thumbInactive: props.thumbInactive,
  thumbActive: props.thumbActive,
  thumbTranslateX: props.thumbTranslateX,
  padding: props.padding,
  checked: props.checked,
});

onMounted(() => {
  if (props.compact) setCompactMode();
});

function setCompactMode() {
  Object.assign(state, {
    base: props.thumbBase,
    height: '',
    // Thumb inherits track styles
    thumbInactive: props.stateInactive,
    thumbActive: props.stateActive,
    thumbTranslateX: '',
    padding: '',
  });
}

function toggle() {
  if (props.disabled) return;
  console.log('here: ', state.checked);
  state.checked = !state.checked;
  console.log('here: ', state.checked);
  emits('onCheckedChange', state.checked);
}

const rxTrackState = computed(() => (state.checked ? props.stateActive : props.stateInactive));
const rxThumbState = computed(() =>
  state.checked ? `${state.thumbActive} ${state.thumbTranslateX}` : state.thumbInactive,
);
const rxDisabled = computed(() => (props.disabled ? props.stateDisabled : ''));
</script>

<template>
  <!-- Track -->
  <button
    type="button"
    :class="`${state.base} ${rxTrackState} ${width} ${state.height} ${state.padding} ${rounded} ${hover} ${rxDisabled} ${classes}`"
    role="switch"
    :aria-checked="state.checked"
    :aria-labelledby="labelledby"
    :aria-describedby="describedby"
    tabindex="0"
    @click="toggle"
    data-testid="switch"
  >
    <!-- Input (hidden) -->
    <input
      type="checkbox"
      :id="id"
      :name="name"
      :checked="state.checked"
      class="hidden"
      :disabled="disabled"
    />
    <!-- Thumb -->
    <div
      :class="`${thumbBase} ${rxThumbState} ${thumbRounded} ${thumbTransition} ${thumbEase} ${thumbDuration} ${thumbClasses}`"
    >
      <span v-if="!state.checked && $slots.inactiveChild" :class="iconInactiveBase">
        <slot name="inactiveChild"></slot>
      </span>
      <span v-if="state.checked && $slots.activeChild" :class="iconActiveBase">
        <slot name="activeChild"></slot>
      </span>
    </div>
  </button>
</template>

// packages/skeleton-angular/projects/lib/src/lib/switch/switch.component.ts
import {
  Component,
  ContentChild,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  TemplateRef,
  ViewChild,
} from '@angular/core';
import { SwitchProps } from './types';

@Component({
  selector: 'switch',
  standalone: true,
  imports: [],
  templateUrl: './switch.component.html',
  styleUrl: './switch.component.css',
})
export class Switch {
  @Input({ required: true }) id!: SwitchProps['id'];
  @Input({ required: true }) name!: SwitchProps['name'];
  @Input() checked: SwitchProps['checked'] = false;
  @Input() disabled: SwitchProps['disabled'] = false;
  @Input() compact: SwitchProps['compact'] = false;
  @Input() labelledby?: SwitchProps['labelledby'];
  @Input() describedby?: SwitchProps['describedby'];
  @Input() base: SwitchProps['base'] =
    'inline cursor-pointer transition duration-200';
  @Input() stateInactive: SwitchProps['stateInactive'] =
    'preset-filled-surface-200-800';
  @Input() stateActive: SwitchProps['stateActive'] =
    'preset-filled-primary-500';
  @Input() stateDisabled: SwitchProps['stateDisabled'] =
    'opacity-50 cursor-not-allowed';
  @Input() width: SwitchProps['width'] = 'w-10';
  @Input() height: SwitchProps['height'] = 'h-6';
  @Input() padding: SwitchProps['padding'] = 'p-0.5';
  @Input() rounded: SwitchProps['rounded'] = 'rounded-full';
  @Input() hover: SwitchProps['hover'] =
    'hover:brightness-90 dark:hover:brightness-110';
  @Input() classes: SwitchProps['classes'] = '';
  @Input() thumbBase: SwitchProps['thumbBase'] =
    'right-0 aspect-square h-full flex justify-center items-center text-right';
  @Input() thumbInactive: SwitchProps['thumbInactive'] =
    'preset-filled-surface-50-950';
  @Input() thumbActive: SwitchProps['thumbActive'] =
    'bg-surface-50 text-surface-contrast-50';
  @Input() thumbRounded: SwitchProps['thumbRounded'] = 'rounded-full';
  @Input() thumbTranslateX: SwitchProps['thumbTranslateX'] = 'translate-x-4';
  @Input() thumbTransition: SwitchProps['thumbTransition'] = 'transition';
  @Input() thumbEase: SwitchProps['thumbEase'] = 'ease-in-out';
  @Input() thumbDuration: SwitchProps['thumbDuration'] = 'duration-200';
  @Input() thumbClasses: SwitchProps['thumbClasses'] = '';
  @Input() iconInactiveBase: SwitchProps['iconInactiveBase'] =
    'pointer-events-none';
  @Input() iconActiveBase: SwitchProps['iconActiveBase'] =
    'pointer-events-none';

  // Events - This are @Output() in Angular, found in the properties of the component
  // onCheckedChange: () => {}
  @Output() onCheckedChange = new EventEmitter<boolean>();

  // Snippets - This is achieved through (named) content projection 
  // inactiveChild,
  // activeChild
  @ContentChild('inactiveChild', { static: true }) inactiveChild!: ElementRef;
  @ContentChild("activeChild", { static: true }) activeChild!: ElementRef;


  ngOnInit() {
    this.checked = this.checked;
    if (this.compact) {
      this.setCompactMode();
    }
    console.log(this.activeChild);
    console.log(this.inactiveChild);
  }

  setCompactMode() {
    this.base = this.thumbBase;
    this.height = '';
    this.thumbInactive = this.stateInactive;
    this.thumbActive = this.stateActive;
    this.thumbTranslateX = '';
    this.padding = '';
  }

  toggle() {
    if (this.disabled) return;
    this.checked = !this.checked;
    this.onCheckedChange.emit(this.checked);
  }

  get rxTrackState(): string {
    const computed = this.checked ? this.stateActive : this.stateInactive;
    return computed ?? '';
  }

  get rxThumbState(): string {
    const computed = this.checked
      ? `${this.thumbActive} ${this.thumbTranslateX}`
      : this.thumbInactive;
    return computed ?? '';
  }

  get rxDisabled(): string {
    const computed = this.disabled ? this.stateDisabled : '';
    return computed ?? '';
  }

  get buttonClass(): string {
    return `${this.base} ${this.rxTrackState} ${this.width} ${this.height} ${this.padding} ${this.rounded} ${this.hover} ${this.rxDisabled} ${this.classes}`;
  }

  get thumbClass(): string {
    return `${this.thumbBase} ${this.rxThumbState} ${this.thumbRounded} ${this.thumbTransition} ${this.thumbEase} ${this.thumbDuration} ${this.thumbClasses}`;
  }
}

<button
  type="button"
  [class]="buttonClass"
  role="switch"
  [attr.aria-checked]="checked"
  [attr.aria-labelledby]="labelledby"
  [attr.aria-describedby]="describedby"
  tabindex="0"
  (click)="toggle()"
  data-testid="switch"
>
  <!-- Input (hidden) -->
  <input
    type="checkbox"
    [id]="id"
    [name]="name"
    [checked]="checked"
    class="hidden"
    [disabled]="disabled"
  />
  <!-- Thumb -->
  <div [class]="thumbClass">
    @if (!checked && inactiveChild) {
      <span [class]="iconInactiveBase">
        <ng-content select="[data-inactive-child]"></ng-content>
      </span>
    }
    @if (checked && activeChild) {
      <span [class]="iconActiveBase">
        <ng-content select="[data-active-child]"></ng-content>
      </span>
    }
  </div>
</button>
