// packages/skeleton-vue/src/lib/components/Progress/Progress.vue
<script lang="ts" setup>
import { computed, watch } from 'vue';
import type { ProgressProps } from './types';

const props = withDefaults(defineProps<ProgressProps>(), {
  value: undefined,
  max: 100,
  labelledBy: '',
  // Root
  base: 'overflow-x-hidden',
  bg: 'bg-surface-200-800',
  width: 'w-full',
  height: 'h-2',
  rounded: 'rounded',
  classes: '',
  // Meter
  meterBase: 'h-full',
  meterBg: 'bg-surface-950-50',
  meterRounded: 'rounded',
  meterTransition: 'transition-[width]',
  meterAnimate: 'animate-indeterminate',
  meterClasses: '',
});

watch(
  () => props.max,
  () => {
    if (props.max < 0) {
      console.warn('The max prop should be greater than or equal to 0');
    }
  },
);

const indeterminate = computed(() => props.value === undefined);
const fillPercentage = computed(
  () => `${indeterminate.value ? 50 : ((props.value! - 0) / (props.max - 0)) * 100}%`,
);
const rxIndeterminate = computed(() => (indeterminate.value ? props.meterAnimate : ''));
</script>

<template>
  <div
    role="progressbar"
    :aria-labelledby="labelledBy"
    :aria-valuenow="value"
    aria-valuemin="0"
    :aria-valuemax="max"
    :class="[base, bg, width, height, rounded, classes]"
  >
    <div
      :class="[meterBase, meterBg, meterRounded, meterTransition, rxIndeterminate, meterClasses]"
      :style="{ width: fillPercentage }"
    ></div>
  </div>
</template>

// packages/skeleton-angular/projects/lib/src/lib/components/progress/progress.component.ts
import { Component, Input, SimpleChanges } from '@angular/core';
import { ProgressProps } from './types';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'skeleton-progress',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './progress.component.html',
  styleUrl: './progress.component.css',
})
export class Progress {
  @Input() value: ProgressProps['value'] = undefined;
  @Input() max: ProgressProps['max'] = 100;
  @Input() labelledBy: ProgressProps['labelledBy'] = '';
  // Root
  @Input() base: ProgressProps['base'] = 'overflow-x-hidden';
  @Input() bg: ProgressProps['bg'] = 'bg-surface-200-800';
  @Input() width: ProgressProps['width'] = 'w-full';
  @Input() height: ProgressProps['height'] = 'h-2';
  @Input() rounded: ProgressProps['rounded'] = 'rounded';
  @Input() classes: ProgressProps['classes'] = '';
  // Meter
  @Input() meterBase: ProgressProps['meterBase'] = 'h-full';
  @Input() meterBg: ProgressProps['meterBg'] = 'bg-surface-950-50';
  @Input() meterRounded: ProgressProps['meterRounded'] = 'rounded';
  @Input() meterTransition: ProgressProps['meterTransition'] =
    'transition-[width]';
  @Input() meterAnimate: ProgressProps['meterAnimate'] =
    'animate-indeterminate';
  @Input() meterClasses: ProgressProps['meterClasses'] = '';
  
  ngOnChanges(changes: SimpleChanges): void {
    if (changes['max'] && changes['max'].currentValue < 0) {
      console.warn('The max prop should be greater than or equal to 0');
    }
  }

  get indeterminate() {
    return this.value === undefined
  }

  get fillPercentage() {
    return `${this.indeterminate ? 50 : ((this.value! - 0) / (this.max! - 0)) * 100}%`;
  }

  get rxIndeterminate() {
    return this.indeterminate ? this.meterAnimate : '';
  }

}

<div
  role="progressbar"
  [attr.aria-labelledby]="labelledBy"
  [attr.aria-valuenow]="value"
  aria-valuemin="0"
  [attr.aria-valuemax]="max"
  [ngClass]="[base, bg, width, height, rounded, classes]"
>
  <div
    [ngClass]="[
      meterBase,
      meterBg,
      meterRounded,
      meterTransition,
      rxIndeterminate,
      meterClasses
    ]"
    [ngStyle]="{ width: fillPercentage }"
  ></div>
</div>
