// packages/skeleton-vue/src/lib/components/Navigation/NavBar.vue
<script lang="ts" setup>
import { reactive } from 'vue';
import { setNavigationContext } from './context';
import type { NavBarProps } from './types';

const emits = defineEmits<{
  onChange: [value: string];
  'update:value': [value: string];
}>();

const props = withDefaults(defineProps<NavBarProps>(), {
  value: '',
  // Root
  base: 'h-full flex flex-col',
  background: 'preset-filled-surface-100-900',
  width: 'min-w-[320px] w-full',
  height: 'h-20',
  padding: 'p-1',
  classes: '',
  // Tiles
  tilesBase: 'flex-1 flex',
  tilesFlexDirection: '',
  tilesJustify: 'justify-center',
  tilesItems: 'items-center',
  tilesGap: 'gap-1',
  tilesClasses: '',
  // Events - This are Emits in Vue, found in the defineEmits in the script
  // onchange
  // Snippets - This are named slots in Vue, found in the template
  // children
});

const state = reactive({
  value: props.value,
});

function onSelectionHandler(id: string) {
  state.value = id;
  emits('onChange', id);
  emits('update:value', id);
}

// Context
setNavigationContext({
  parent: 'bar',
  get value() {
    return props.value;
  },
  expanded: false,
  onSelectionHandler,
});
</script>

<template>
  <aside
    :class="`${base} ${background} ${width} ${height} ${padding} ${classes}`"
    data-testid="nav-bar"
  >
    <nav
      v-if="$slots.default"
      :class="`${tilesBase} ${tilesFlexDirection} ${tilesJustify} ${tilesItems} ${tilesGap} ${tilesClasses}`"
    >
      <slot></slot>
    </nav>
  </aside>
</template>

// packages/skeleton-angular/projects/lib/src/lib/components/navigation/nav-bar/nav-bar.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NavContextService } from '../nav-context.service';
import { NavBarProps, NavigationParent } from '../types';

@Component({
  selector: 'skeleton-nav-bar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './nav-bar.component.html',
  styleUrl: './nav-bar.component.css',
  providers: [NavContextService],
})
export class NavBar {
  private _value: NavBarProps['value'] = '';

  @Input()
  get value(): NavBarProps['value'] {
    return this._value;
  }
  set value(val: NavBarProps['value']) {
    this._value = val;
    this.ctx.value.set(val || '');
    this.valueChange.emit(val);
    this.onChange.emit(val);
  }

  @Output() valueChange = new EventEmitter<any>();

  // Root
  @Input() base: NavBarProps['base'] = 'h-full flex flex-col';
  @Input() background: NavBarProps['background'] =
    'preset-filled-surface-100-900';
  @Input() width: NavBarProps['width'] = 'min-w-["320px"] w-full';
  @Input() height: NavBarProps['height'] = 'h-20';
  @Input() padding: NavBarProps['padding'] = 'p-1';
  @Input() classes: NavBarProps['classes'] = '';
  // Tiles
  @Input() tilesBase: NavBarProps['tilesBase'] = 'flex-1 flex';
  @Input() tilesFlexDirection: NavBarProps['tilesFlexDirection'] = '';
  @Input() tilesJustify: NavBarProps['tilesJustify'] = 'justify-center';
  @Input() tilesItems: NavBarProps['tilesItems'] = 'items-center';
  @Input() tilesGap: NavBarProps['tilesGap'] = 'gap-1';
  @Input() tilesClasses: NavBarProps['tilesClasses'] = '';
  // Events - This are @Output() in Angular, found in the properties of the component
  // onchange
  @Output() onChange = new EventEmitter<string>();

  // Snippets - This is achieved through (named) content projection
  // children

  onSelectionHandler(id: string) {
    this.onChange.emit(id);
  }

  constructor(private ctx: NavContextService) {
    this.ctx.parent.set(NavigationParent.Bar);
    this.ctx.value.set(this.value || '');
    this.ctx.expanded.set(false);
    this.ctx.onSelectionHandler = this.onSelectionHandler.bind(this);
  }
}

<aside
  [ngClass]="[base, background, width, height, padding, classes]"
  data-testid="nav-bar"
>
  <nav
    [ngClass]="[
      tilesBase,
      tilesFlexDirection,
      tilesJustify,
      tilesItems,
      tilesGap,
      tilesClasses
    ]"
  >
    <ng-content></ng-content>
  </nav>
</aside>
