// packages/skeleton-vue/src/lib/components/Navigation/NavRail.vue
<script lang="ts" setup>
import { computed, reactive } from 'vue';
import { setNavigationContext } from './context';
import type { NavRailProps } from './types';

const emits = defineEmits<{
  onChange: [value: string];
  'update:value': [value: string];
}>();

const props = withDefaults(defineProps<NavRailProps>(), {
  value: '',
  expanded: false,
  // Root
  base: 'h-full flex flex-col',
  background: 'preset-filled-surface-100-900',
  padding: 'p-1',
  width: 'w-24',
  widthExpanded: 'w-64',
  height: 'h-full',
  classes: '',
  // Header
  headerBase: 'flex',
  headerFlexDirection: 'flex-col',
  headerJustify: 'justify-center',
  headerItems: 'items-center',
  headerGap: 'gap-1',
  headerClasses: '',
  // Tiles
  tilesBase: 'flex-1 flex',
  tilesFlexDirection: 'flex-col',
  tilesJustify: 'justify-center',
  tilesItems: 'items-center',
  tilesGap: 'gap-1',
  tilesClasses: '',
  // Footer
  footerBase: 'flex',
  footerFlexDirection: 'flex-col',
  footerJustify: 'justify-center',
  footerItems: 'items-center',
  footerGap: 'gap-1',
  footerClasses: '',
  // Events - This are Emits in Vue, found in the defineEmits in the script
  // onchange,
  // Snippets - This are named slots in Vue, found in the template
  // header,
  // tiles,
  // footer,
});

const state = reactive({
  value: props.value,
});

function onSelectionHandler(id: string) {
  state.value = id;
  emits('onChange', id);
  emits('update:value', id);
}

// Context
setNavigationContext({
  parent: 'rail',
  get value() {
    return props.value;
  },
  get expanded() {
    return props.expanded;
  },
  onSelectionHandler,
});

// Reactive
const rxWidth = computed(() => (props.expanded ? props.widthExpanded : props.width));
</script>

<template>
  <aside
    :class="`${base} ${background} ${height} ${padding} ${rxWidth} ${classes}`"
    data-testid="nav-rail"
  >
    <header
      v-if="$slots.header"
      :class="`${headerBase} ${headerFlexDirection} ${headerJustify} ${headerItems} ${headerGap} ${headerClasses}`"
    >
      <slot name="header" />
    </header>
    <!-- Tiles -->
    <nav
      v-if="$slots.tiles"
      :class="`${tilesBase} ${tilesFlexDirection} ${tilesJustify} ${tilesItems} ${tilesGap} ${tilesClasses}`"
    >
      <slot name="tiles" />
    </nav>
    <!-- Footer -->
    <footer
      v-if="$slots.footer"
      :class="`${footerBase} ${footerFlexDirection} ${footerJustify} ${footerItems} ${footerGap} ${footerClasses}`"
    >
      <slot name="footer" />
    </footer>
  </aside>
</template>

// packages/skeleton-angular/projects/lib/src/lib/components/navigation/nav-rail/nav-rail.component.ts
import { CommonModule, NgTemplateOutlet } from '@angular/common';
import {
  Component,
  ContentChild,
  EventEmitter,
  HostBinding,
  Input,
  Output,
  SimpleChanges,
  TemplateRef,
} from '@angular/core';
import { NavContextService } from '../nav-context.service';
import { NavigationParent, NavRailProps } from '../types';

@Component({
  selector: 'skeleton-nav-rail',
  standalone: true,
  imports: [NgTemplateOutlet, CommonModule],
  templateUrl: './nav-rail.component.html',
  styleUrl: './nav-rail.component.css',
  providers: [NavContextService],
})
export class NavRail {
  private _value: NavRailProps['value'] = '';

  @Input()
  get value(): NavRailProps['value'] {
    return this._value;
  }
  set value(val: NavRailProps['value']) {
    this._value = val;
    this.ctx.value.set(val || '');
    this.valueChange.emit(val);
    this.onChange.emit(val);
  }

  @Output() valueChange = new EventEmitter<any>();

  @Input() expanded: NavRailProps['expanded'] = false;
  // Root
  @Input() base: NavRailProps['base'] = 'h-full flex flex-col';
  @Input() background: NavRailProps['background'] =
    'preset-filled-surface-100-900';
  @Input() padding: NavRailProps['padding'] = 'p-1';
  @Input() width: NavRailProps['width'] = 'w-24';
  @Input() widthExpanded: NavRailProps['widthExpanded'] = 'w-64';
  @Input() height: NavRailProps['height'] = 'h-full';
  @Input() classes: NavRailProps['classes'] = '';
  // Header
  @Input() headerBase: NavRailProps['headerBase'] = 'flex';
  @Input() headerFlexDirection: NavRailProps['headerFlexDirection'] =
    'flex-col';
  @Input() headerJustify: NavRailProps['headerJustify'] = 'justify-center';
  @Input() headerItems: NavRailProps['headerItems'] = 'items-center';
  @Input() headerGap: NavRailProps['headerGap'] = 'gap-1';
  @Input() headerClasses: NavRailProps['headerClasses'] = '';
  // Tiles
  @Input() tilesBase: NavRailProps['tilesBase'] = 'flex-1 flex';
  @Input() tilesFlexDirection: NavRailProps['tilesFlexDirection'] = 'flex-col';
  @Input() tilesJustify: NavRailProps['tilesJustify'] = 'justify-center';
  @Input() tilesItems: NavRailProps['tilesItems'] = 'items-center';
  @Input() tilesGap: NavRailProps['tilesGap'] = 'gap-1';
  @Input() tilesClasses: NavRailProps['tilesClasses'] = '';
  // Footer
  @Input() footerBase: NavRailProps['footerBase'] = 'flex';
  @Input() footerFlexDirection: NavRailProps['footerFlexDirection'] =
    'flex-col';
  @Input() footerJustify: NavRailProps['footerJustify'] = 'justify-center';
  @Input() footerItems: NavRailProps['footerItems'] = 'items-center';
  @Input() footerGap: NavRailProps['footerGap'] = 'gap-1';
  @Input() footerClasses: NavRailProps['footerClasses'] = '';
  // Events - This are @Output() in Angular, found in the properties of the component
  // onchange,
  @Output() onChange = new EventEmitter<string>();
  // Snippets - This is achieved through (named) content projection
  // header,
  // tiles,
  // footer,
  @ContentChild('header', { read: TemplateRef }) header!: TemplateRef<any>;
  @ContentChild('tiles', { read: TemplateRef }) tiles!: TemplateRef<any>;
  @ContentChild('footer', { read: TemplateRef }) footer!: TemplateRef<any>;

  onSelectionHandler(id: string) {
    this.onChange.emit(id);
  }

  constructor(private ctx: NavContextService) {
    this.ctx.parent.set(NavigationParent.Rail);
    this.ctx.value.set(this.value || '');
    this.ctx.expanded.set(false);
    this.ctx.onSelectionHandler = this.onSelectionHandler.bind(this);
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['expanded']) {
      this.ctx.expanded.set(changes['expanded'].currentValue);
    }
  }

  get rxWidth() {
    return this.ctx.expanded() ? this.widthExpanded : this.width;
  }

  @HostBinding('class')
  get hostClasses() {
    return this.rxWidth;
  }
}

<aside
  [ngClass]="[base, background, height, padding, rxWidth, classes]"
  data-testid="nav-rail"
>
  @if (header) {
    <header
      [ngClass]="[
        headerBase,
        headerFlexDirection,
        headerJustify,
        headerItems,
        headerGap,
        headerClasses
      ]"
    >
      <ng-container [ngTemplateOutlet]="header"></ng-container>
    </header>
  }
  <!-- Tiles -->
  @if (tiles) {
    <nav
      [ngClass]="[
        tilesBase,
        tilesFlexDirection,
        tilesJustify,
        tilesItems,
        tilesGap,
        tilesClasses
      ]"
    >
      <ng-container [ngTemplateOutlet]="tiles"></ng-container>
    </nav>
  }
  <!-- Footer -->
  @if (footer) {
    <footer
      [ngClass]="[
        footerBase,
        footerFlexDirection,
        footerJustify,
        footerItems,
        footerGap,
        footerClasses
      ]"
    >
      <ng-container [ngTemplateOutlet]="footer"></ng-container>
    </footer>
  }
</aside>
